version: '3.8'
services:
  payment-service:
    build: .
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      app.name: PaymentService
    networks:
      - local-sub-net



networks:
  local-sub-net:
    driver: bridge
